services:
  # React Frontend with WebRTC Signaling (Main Frontend)
  frontend:
    build:
      context: ./frontend-react
    ports:
      - "3000:3000"    # HTTP
      - "3443:3443"    # HTTPS
    environment:
      - NODE_ENV=production
      - HOST_IP=10.71.252.230
      - BACKEND_URL=http://backend:8080
    restart: always
    networks:
      - webrtc-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Python Backend with Object Detection
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - HOST_IP=10.71.252.230
    restart: always
    networks:
      - webrtc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  webrtc-network:
    driver: bridge

